### ISSUE TITLE
Spot is running in the background

### ISSUE THREAD

**Issue by ondras12345** [xou816/spot#132]
**Describe the bug**
After Spot is closed for the first time, there is a popup warning about it running in the background. After "Force quit" is clicked, this choice is remembered and the next time Spot is launched and quit, it stays in the background for a couple of seconds and then receives SIGKILL.

This choice can later be changed in `Settings > Applications > Spot > Integration > Run in background` in Ubuntu.

I _think_ this popup comes from xdg-desktop-portal, but I'm not really sure.

A subsequent question would be how do I close Spot if I allowed it to run in the background? I can click the notification with media controls and the Spot window is opened again, but it still does not terminate the process when closed. I found that ctrl-Q works, but I think there should be a way to do this from the GUI.

**To Reproduce**
1. Install Spot with flatpak on Ubuntu 20.04
2. Start Spot and sign in to your account. The bug does not occur when the user is not signed in.
3. Close the Spot window
4. Wait for a couple of seconds
5. See notification and popup

**Expected behavior**
The popup should not appear, or it should contain an explanation of why the app needs to run in the background.
Spot should have an icon in the system tray or provide other means to close it.

**Screenshots**
![Screenshot from 2021-03-07 15-12-12](https://user-images.githubusercontent.com/44524735/110242994-c8f0b580-7f58-11eb-9eb6-ba67ec37fb37.png)

**General information:**
 - Distribution: Ubuntu 20.04
 - Installation method: Flathub
 - Version: 0.1.9
 - Device used: desktop

**Comment by xou816** [comment]
Hi! Thanks for the detailed report!

This is indeed intentional, but you're right, there are several issues there.

> I found that ctrl-Q works, but I think there should be a way to do this from the GUI.

There is also a Quit item in some DEs such as GNOME, but I should a Quit item in the in-app menu. I think Lollypop is a good example of how to handle this; if playback is stopped when closing the window, then the app exits, otherwise it runs in the background.

> The popup should not appear, or it should contain an explanation of why the app needs to run in the background.

Probably this, yeah, otherwise people might hit force quit instinctively the first time around and end up disappointed when the app is killed after 30s of background usage. [ashpd](https://github.com/bilelmoussaoui/ashpd/) looks very promising for that (and has a pretty cool name).

**Comment by xou816** [comment]
Closing this for now if that's okay with you, feel free to reopen otherwise!

I might look into requesting authorization for background exec in the future, but right now (0.1.10) it only keeps running if something is playing, which should make it obvious why it needs to run in the background!
