### ISSUE TITLE
UI freezes when loading large playlists

### ISSUE THREAD

**Issue by klingtnet** [xou816/spot#154]
**Describe the bug**

When trying to open a [large playlist](https://open.spotify.com/playlist/57dendQnqICUAY1oFg6dao?si=phDSlwbaRZCT8Ej9z2wIQQ) the UI becomes unresponsive, the process is using 100% CPU and eventually freezes.

**To Reproduce**

1. Open a large playlist, e.g. [this one](https://open.spotify.com/playlist/57dendQnqICUAY1oFg6dao?si=phDSlwbaRZCT8Ej9z2wIQQ) (if it is not public please tell me)

**Expected behavior**

The playlist should be shown (almost) immediately.

**Screenshots**

~~If applicable, add screenshots to help explain your problem.~~

**General information:**

 - Distribution: Arch Linux kernel 5.11.6
 - Installation method: AUR
 - Version: `0.1.10`
 - Device used: desktop

**Comment by xou816** [comment]
Yeah, we'll have to change the way we've implemented some things if we want to tackle very very large playlists :D thank you for providing a public example by the way, this is helpful!

**Comment by Douile** [comment]
Perhaps we could fix this by separating the backend from the UI, not sure if this is possible but:

- Load just first 20 songs for UI
  - Use scroll loader like for albums etc.
- When the playlist is played load the entire song list into a vector (not seen by UI)
  - As long as this is background threaded shouldn't affect UI
  - The entire playlist needs to be loaded (especially if shuffling)
- As long as pagination is consistent between both we don't need to link them in any way as they will use the same cache files
  - Adds a bit of overhead as parsing the JSON twice
  - Adds memory overhead as well, because songs are stored twice in memory

This is a bit of a hacky solution, and it would move the lag from when you open the playlist to when you start trying to play a song , wouldn't actually get rid of it. To mitigate lag could maybe start loading entire playlist in background once UI is open (would be nice to cancel this if the user leaves playlist UI and has not started playing anything).

What do you think of this @xou816 ? I remember you mentioned something about queues that the official client uses but icr where or what you said exactly.

**Comment by xou816** [comment]
Hi there!

So as it happens I started working on this yesterday (https://github.com/xou816/spot/tree/fix/long-playlists), but you make some good points worth discussing!

For now I chose to not load the full playlist in the queue either -- I don't want to assume it will be reasonably sized at all (still could be costly in terms of requests+memory, even if the UI does not directly suffer from it). Instead, when some Nth track is reached, more songs are loaded (this does duplicate some logic -- now the Now playing view also knows how to load songs when source=playlist)

> The entire playlist needs to be loaded (especially if shuffling)

Shuffling is an issue though, you're right. I intended to choose a large enough size such that it feels random (first batch shuffled, then second batch shuffled, etc) but this is not ideal :/ This could probably be improved by loading a random batch everytime (we can know the size of the playlist ahead of time I believe).

> As long as pagination is consistent between both we don't need to link them in any way as they will use the same cache files 

They can even be fully independent (and they should be; one is about browsing stuff, the other about playing that).

--

So yeah, my current solution is not good for shuffling and sorting :/ I am not sure about loading the full playlist though. This one for instance has 8k songs, and we can't query more than 100 songs at once according to the documentation, so that would require  about 80 requests :/ 

Sorting will have the same issues :(

**Comment by xou816** [comment]
As for the WIP implementation, there are a few things that could be improved to keep working with small batches:
- right now, hitting play anywhere has the view adding visible songs to the queue; instead, there should probably be some kind of abstraction, a loadable source of songs, that would be used when browsing but also by the play queue. This abstraction would know how to load a large, paginated list of songs (given a spotify client instance), and how to load a semi random portion of it (load a random batch, shuffle it)
- the play queue allows theoretically for an unlimited number of songs; it should instead be limited and use the loadable source thingy above to load more content when needed (partially implemented), and it should probably remove items from the front of the list too (not implemented)

**Comment by Douile** [comment]
Ah nice one, looks good so far. I was going to work on sorting soon but I will leave it till after you have added this (no rush). 

For the random part of songs we would need to know how long the whole playlist is. While I don't think the API returns this by default, I am pretty sure this is possible if we use the GraphQL like items search param.

**Comment by xou816** [comment]
> For the random part of songs we would need to know how long the whole playlist is.

I think I see it as "total"!

**Comment by Douile** [comment]
Ah, yes I missed that.

**Comment by xou816** [comment]
This should be much better already with Gtk4 Listviews, I'll have to do some proper testing

**Comment by xou816** [comment]
closing for now following the improvments brought with listviews, feel free to reopen

**Comment by zopieux** [comment]
I'm not sure what was the severity of this issue in 2021, but as a new user, I immediately noticed the 200+ms lag on loading even medium-sized playlists (in the video below, [the first pl](https://open.spotify.com/playlist/37i9dQZF1DZ06evO02Y0rS) has 51 songs and [the second](https://open.spotify.com/playlist/5Q02oVX8s3S6oYPj7r2B8N) has 106 songs). I wouldn't consider these numbers large.

![spot_load_playlist_2](https://user-images.githubusercontent.com/81353/169174606-78931eae-bc33-47b0-8e01-fe49cbfb8aab.gif)

Any chance this data could be preloaded / cached / otherwise improved to remove the noticeable loading pause? Thanks!
