### ISSUE TITLE
playlists with offline tracks don't fully load

### ISSUE THREAD

**Issue by LennyPenny** [xou816/spot#190]
**Describe the bug**
After playlists that have offline tracks are now finally working I noticed that these playlists currently only show a subset of actual songs in spot. 

This seems to be related to pagination, as only the first 100 tracks are loaded in this case, even though the playlist has over 100 songs. 

**To Reproduce**
1. Open playlist https://api.spotify.com/v1/playlists/5FKAf83T8zZHBDu2xEgPNg in spot
2. Only the first 85 tracks are displayed in spot, even though there are 90+ non offline tracks

**Expected behavior**
See all non offline tracks

**General information:**
 - Distribution: fedora 34
 - Flathub
 - Version 0.13.0

Top is the content of the `0_100.json` of the playlist, indicating that there is a second page. 
Bottom is all cached files of the playlist, indicating that only the first page (`0_100`) was fetched, but not the second. 

![image](https://user-images.githubusercontent.com/4027243/114470013-6f7e4500-9bee-11eb-9623-584420f21c92.png)

**Comment by xou816** [comment]
Oh I see what's happening :( I'm assuming in the code that since we got fewer items than requrested we reached the end of the playlist :(

I have a branch I've been working on for a while where I'll rework playlist loading, I'll make sure to fix this at the same time!

In any case, thank you for the detailed report, it really helps! I'm sorry for your continued trouble with these playlists.

**Comment by xou816** [comment]
fixed in upcoming 0.1.14!
