### ISSUE TITLE
Spot does not respect system theme

### ISSUE THREAD

**Issue by idontlikecaesar** [xou816/spot#209]
Spot stays in Adwaita dark even though I use Adwaita light.

**Comment by idontlikecaesar** [comment]
Thank you for your quick response! It is not weird but it is not the expected behavior.

**Comment by schlauerlauer** [comment]
I think the dark theme by default is fine,
but when I change the system theme to Adwaita-dark Spot switches to the light theme :smile:
and I can't change it to dark again with the `keyfile`

So Spot uses the opposite to the system theme?
(only a nitpick for me though)

**Comment by xou816** [comment]
Ahah that's... weird! I can't reproduce the issue on my end, if I use Adwaita, it will use the light or dark variant based  on my gsettings, and if I use Adwaita-dark, it's always dark :thinking: 

I suppose you're using the flatpak version? Is there anything special about your install? (modified Adwaita theme, something else...?)

**Comment by schlauerlauer** [comment]
Okay I tried it again and now it respects the Adwaita theme (but changing the setting in the `keyfile` does nothing).
Weird.. I rebooted maybe that helped :slightly_smiling_face: 

Yes it's the flatpak version
and no there's nothing special about the Adwaite theme.

**Comment by lobau** [comment]
I have the same issue. I use Adwaita Light but Spot is in dark. If I switch the system in Dark mode, Spot becomes Light. I wish Spot would just follow the system theme :-)
![Screenshot from 2021-06-10 18-58-29](https://user-images.githubusercontent.com/6750584/121619741-e6cd2b00-ca1d-11eb-8ab1-0bc9dc2d6ced.png)

**Comment by xou816** [comment]
Definitely weird ahah, are you using the same distro per chance? Do you have the same issue with other Flatpak apps? (one that allows switching to the dark theme preferably).

I am not doing anything special with the theme (just exposing a gsetting to prefer the dark variant). 

Things that could be happening I think:
- Adwaita-dark acts as a theme for which the dark variant is the light version of Adwaita (unlikely);
- Adwaita-dark is seen as a theme fully distinct from Adwaita, and if it has no counterpart on the flatpak side of things, flatpak defaults to using Adwaita (but no longer respects the setting to prefer the dark variant for some reason).

If the latter is correct, it might be worth checking if you have Adwaita-dark installed on your flatpak install:
$ flatpak list | grep theme

**Comment by lobau** [comment]
I'm using PureOS  (GNOME 3.38.4) with the default Adwaita theme.
I have Adwaita Dark installed. Spot looks great in dark mode on my system :)
The problem is that to be in dark mode my whole system has to be in light mode.

![Screenshot from 2021-06-11 11-12-14](https://user-images.githubusercontent.com/6750584/121731836-4c64fa00-caa6-11eb-81b2-2883403c003b.png)

Here is the output of the command:
`$ flatpak list | grep theme
Adwaita theme	org.kde.KStyle.Adwaita		5.15	flathub	system
`

I tried to find another app that enforce a dark theme by defaut to see if other apps behave like this but I cannot find one. Do you know of another gtk app that enforce a dark theme?

**Comment by ondras12345** [comment]
> Do you know of another gtk app that enforce a dark theme?

[Shortwave](https://flathub.org/apps/details/de.haeckerfelix.Shortwave)

**Comment by xou816** [comment]
Thanks for the details! Looks like Adwaita-dark is not installed on the flatpak side for your system. Try installing it and see if it helps :)

**Comment by idontlikecaesar** [comment]
@xou816 do you have any plans to release it as apt package?

**Comment by lobau** [comment]
> Thanks for the details! Looks like Adwaita-dark is not installed on the flatpak side for your system. Try installing it and see if it helps :)

It might help Spot looks Dark while the rest of the system is dark too, but I'm not sure how that would help the original request of this bug, which is to respect the system theme?
I would like to use Spot in light mode, as the rest of my system is in light mode, which I believe is the request of the OP too :)

**Comment by xou816** [comment]
There are two things at play here, which is why it gets confusing, let me summarize (I should probably add something to the README, it's not the first theme this topic is brought up):

- Spot exposes a gsetting to prefer the dark variant of your Gtk theme (similarly to other Gtk applications, eg Lollypop); the default value is "true" which is why when everything else works correctly theme-wise, Spot uses the dark theme (see https://github.com/xou816/spot/issues/187#issuecomment-816530939 );

- for flatpak apps to use a custom Gtk theme (that includes Adwaita-dark!), the theme has to be installed on the flatpak side as well (org.gtk.Gtk3theme.Adwaita-dark in that case)

Hope this makes things clearer :)
