### ISSUE TITLE
AUR build fails when running meson test in check stage

### ISSUE THREAD

**Issue by appelgriebsch** [xou816/spot#252]
I run the PKGBUILD from Arch AUR on my arm64 system and it came back with an issue in the check stage, which is running a meson test...

```
==> Starting check()...
ninja: Entering directory `/build/spot-client/src/build'
ninja: no work to do.
1/4 Validate schema file       OK              0.05s
2/4 Clippy                     FAIL            0.12s   exit status 101
>>> MALLOC_PERTURB_=131 /bin/bash /build/spot-client/src/spot-0.1.15/build-aux/clippy.sh /build/spot-client/src/spot-0.1.15 /build/spot-client/src/build false
3/4 Validate appstream appdata OK              1.92s
4/4 Unit tests                 OK             46.47s
```

Any idea what this is all about and if I can just skip those steps?

**Comment by xou816** [comment]
Hi!

What target are you building for exactly? (as seen in rustup target list for instance) And what commit are you building from?

Otherwise exist status 101 seems to be the result of a panic!, which I don't think happens for failing tests. Is your toolchain (and clippy) up to date? 

Maybe you could also run meson with the verbose flag?

**Comment by appelgriebsch** [comment]
Hey, I'm building for `aarch64-unknown-linux-gnu` using the latest release tar.gz (0.1.15) on `rust-1:1.53.0`.

**Comment by xou816** [comment]
Thanks for the details!

 If I understand correctly, `spot-client/src/build` is the ninja target directory, and `spot-client/src/spot-0.1.15` is where the sources are cloned, right? So maybe indeed, when going up from the `spot-client/src/build` it misses the actual source root. Does it mean you have an additional meson.build file in `spot-client/src`?

I will try to build with a similar layout and see if I run into the same issue!

I think you can try modifying the clippy step so that the path to Cargo.toml is given explicitly: 

```
cargo clippy --manifest-path "$SRC"/Cargo.toml -- -D warnings -A clippy::module_inception
``` 

Otherwise, to answer your original concern, it's absolutely fine to skip these tests :)

**Comment by appelgriebsch** [comment]
Thanks!

**Comment by xou816** [comment]
More reports here, I could reproduce using the PKGBUILD here https://aur.archlinux.org/packages/spot-client/#comment-815373
