### ISSUE TITLE
[Feature request] Make better use of sidepanel, option to list playlists

### ISSUE THREAD

**Issue by jacksongoode** [xou816/spot#287]
Right now, unless there are plans to make more use of the side panel, I think it would be nice to have a list of playlists. This might require the introduction of some line barriers to divide the collections (Library, Playlists, and Now Playing) and the playlists themselves.

**Comment by xou816** [comment]
Fair enough, that'd be handy indeed! lots of wasted space otherwise

**Comment by abegert** [comment]
I have started working on this, hope that's okay. My idea is to have the playlists in an expandable treeview, which is collapsed by default.
I'm also planning on adding the already mentioned line barriers.

**Comment by abegert** [comment]
> > I have started working on this, hope that's okay. My idea is to have the playlists in an expandable treeview, which is collapsed by default. I'm also planning on adding the already mentioned line barriers.
> 
> Great to hear! However, I'm not sure if having it be expandable and collapsed by default is the way to go.

What would you prefer? Moving Playlists to the bottom and then adding items for each playlist underneath?

**Comment by jannuary** [comment]
> What would you prefer? Moving Playlists to the bottom and then adding items for each playlist underneath?

Yeah, that sounds good.
In more general thoughts about sidebar, something like this would be nice:
![Sidebar](https://user-images.githubusercontent.com/27908024/142183297-04a493f7-16ea-4856-934c-358d7e2a6129.png)

**Comment by xou816** [comment]
That is lovely, thank you both! I generally trust @jannuary with the design stuff 😄 mock-up looks good to me! If that's okay with everyone I think that's the way to go! 
Thank you for your dedication @abegert hmu if you have any technical concerns! I think the current sidebar is a bit messy code wise

**Comment by abegert** [comment]
I really like the mockup, @jannuary!
Correct me if I am wrong, but AFAIK, creating new playlists is not implemented in spot yet, so I will not be adding the 'New Playlist' item for now.

**Comment by abegert** [comment]
> > What would you prefer? Moving Playlists to the bottom and then adding items for each playlist underneath?
> 
> Yeah, that sounds good. In more general thoughts about sidebar, something like this would be nice: ![Sidebar](https://user-images.githubusercontent.com/27908024/142183297-04a493f7-16ea-4856-934c-358d7e2a6129.png)

I've been making some progress on this issue. However, I couldn't find the icons you are using in the mockup. I tried to find them under /usr/share/icons. Where did you find them? And if they are gnome icons and I just overlooked them, what are their names?

**Comment by jannuary** [comment]
> > > What would you prefer? Moving Playlists to the bottom and then adding items for each playlist underneath?
> > 
> > Yeah, that sounds good. In more general thoughts about sidebar, something like this would be nice: (...)
> 
> 
> I've been making some progress on this issue. However, I couldn't find the icons you are using in the mockup. I tried to find them under /usr/share/icons. Where did you find them? And if they are gnome icons and I just overlooked them, what are their names?

They're from icon-development-kit, you can use [Icon Library](https://flathub.org/apps/details/org.gnome.design.IconLibrary) to get these.

We already bundle some icons, so you'll just need to update the resource file to include them. Feel free to ask if you have other questions.

**Comment by abegert** [comment]
> > > > What would you prefer? Moving Playlists to the bottom and then adding items for each playlist underneath?
> > > 
> > > 
> > > Yeah, that sounds good. In more general thoughts about sidebar, something like this would be nice: (...)
> > 
> > 
> > I've been making some progress on this issue. However, I couldn't find the icons you are using in the mockup. I tried to find them under /usr/share/icons. Where did you find them? And if they are gnome icons and I just overlooked them, what are their names?
> 
> They're from icon-development-kit, you can use [Icon Library](https://flathub.org/apps/details/org.gnome.design.IconLibrary) to get these.
> 
> We already bundle some icons, so you'll just need to update the resource file to include them. Feel free to ask if you have other questions.

Thanks, that was helpful! I want to clean up my code a little before opening the PR. While I do that, we can discuss if there are some UI adjustments we want to make and discuss the changes in general.

### UI
The playlists are displayed in the same order as in the playlists view where we can see all playlists with their cover.

![image](https://user-images.githubusercontent.com/91668665/144650242-d267d199-a9ed-42b0-94fd-1da5e1d00002.png)

As you can see, I tried to stick closely to the mock-up.

The `playlists` entry is still clickable like before, the entries for individual playlists are obviously also clickable and will load the corresponding playlist.

### Code
I will try to describe the approach so you can judge whether it makes sense to do it like that before going into actual code review.
My original plan was to write a subclass that inherits from Stack, which would implement a new method for adding items to the stack with not only a title but also an icon. The StackSidebar would then also be subclassed so that it shows the icon, too.
I learned that Stack is not subclassable, so I gave up on that.
What I am doing now is this: After adding widgets to the Stack, I replace the Label widget in each ListBoxRow of the ListBox of StackSidebar with a GtkBox that contains icon and title.
Annoyingly, I have to do that every time a widget is added to the stack, since the StackSideBar will entirely rebuild each time and replace 'my' widgets with conventional labels.


I'm looking forward to hearing what you guys think!

**Comment by jannuary** [comment]
Some nitpicks on design side:
- The playlist header isn't quite right, I'd recommend using .caption-heading style class on it
- I don't think it makes sense for "Playlists" header to be interactable? It's not really something that's done and its styling heavily implies that it is not clickable.

Outside from that, it's looking great 💖

**Comment by abegert** [comment]
> Some nitpicks on design side:
> 
>     * The playlist header isn't quite right, I'd recommend using .caption-heading style class on it
> 
>     * I don't think it makes sense for "Playlists" header to be interactable? It's not really something that's done and its styling heavily implies that it is not clickable.
> 
> 
> Outside from that, it's looking great sparkling_heart

Thanks for both suggestions, I changed the css class and made "Playlists" non-interactable. It's true that the design says "this is not clickable".
I hesitated to make "Playlists" non-interactable since this is now taking away functionality. If @xou816 agrees on this, I guess we could even remove the entire "SavedPlaylists" view, unless there's another point were we still want it to be reachable.
![image](https://user-images.githubusercontent.com/91668665/144763981-2eddac9e-ce20-4647-be42-1d2a8d6d0036.png)

**Comment by xou816** [comment]
> Outside from that, it's looking great :sparkling_heart: 

I agree with the above :p thanks for your work! 

> I will try to describe the approach so you can judge whether it makes sense to do it like that before going into actual code review.

Thanks, this is indeed a good idea to discuss these things, I appreciate it! Too bad the first approach is not really feasible, but that's okay. The second one sounds sounds a bit hacky but maybe I've understood it wrong.

I haven't looked into it very closely, but I'm thinking it might be doable to have our own widget(s) for that sidebar instead of the StackSidebar, if we're going to hack at its internals anyway :p it is (mostly) a listbox, which we could create and configure as we see fit. As long as we have some reference to the StackSwitcher, we don't actually need a StackSidebar to control it -- we can handle our rows being activated and show the relevant child of the Stack. I might be missing something though!

> I hesitated to make "Playlists" non-interactable since this is now taking away functionality. If @xou816 agrees on this, I guess we could even remove the entire "SavedPlaylists" view, unless there's another point were we still want it to be reachable.

That's a good point! It might not be _that_ useful anymore. Still, I think it might be interesting to keep it for two reasons:
- it might be easier to browse and identify a playlist using their cover images, whereas the sidebar only gives a name;
- it could be useful to have an extra item in the sidebar to view all playlists, especially if we want to limit the number of playlists that can appear on the side (which we should probably do). Design wise, I'll let jannuary chime in but maybe it's just a matter of making that access to playlist look more like the other entries, instead of it being a header that happens to be clickable. Maybe it could be another similar icon+label item, where the icon suggests there's more content to browse, and it would appear after all the other playlists?

**Comment by jannuary** [comment]
> Thanks for both suggestions, I changed the css class and made "Playlists" non-interactable. It's true that the design says "this is not clickable".

Sorry, still not right :\ "Playlists" also needs to be insensitive. 

I think it might make sense to have a "Show All" button or something of that nature after the playlists if that is something that's needed.

**Comment by abegert** [comment]
@xou816 The fact that you think it's a bit hacky probably means that you understood it correctly, it **is** a bit hacky. Your suggestion about just instantiating the ListBox ourselves is something I had already considered. I just wanted to go back into the discussion here in case there is an even better solution that I hadn't thought of. I have since started on reworking it that way.

@jannuary Sorry, I don't understand what you mean by 'insensitive'. I first thought it must be another css-class but couldn't find it. Could you explain?

And regarding the 'Show all' functionality: I will limit the number of playlists in the sidebar and add a 'Show all' entry that is clickable and will redirect to what we currently have under "Playlists".

**Comment by jannuary** [comment]
> @jannuary Sorry, I don't understand what you mean by 'insensitive'. I first thought it must be another css-class but couldn't find it. Could you explain?

It's a [property](https://docs.gtk.org/gtk4/property.Widget.sensitive.html), not a class. Insensitive widgets appear "greyed out".

**Comment by abegert** [comment]
> > @jannuary Sorry, I don't understand what you mean by 'insensitive'. I first thought it must be another css-class but couldn't find it. Could you explain?
> 
> It's a [property](https://docs.gtk.org/gtk4/property.Widget.sensitive.html), not a class. Insensitive widgets appear "greyed out".

Thanks, so like this:
![image](https://user-images.githubusercontent.com/91668665/145221978-fd9f599f-5ea2-4f11-968b-1e0f9181bbe7.png)

I'll update this issue again when I have made progress with my refactoring.

**Comment by jannuary** [comment]
Hm, Apple Music seems to have an "All Playlists" buttons before playlists:
![Screenshot_20211211-231643_Firefox.png](https://user-images.githubusercontent.com/27908024/145683701-cf53ad4b-f8fc-497a-8abe-0b1f7924c720.png)

Wonder if that's a better way

**Comment by abegert** [comment]
> Hm, Apple Music seems to have an "All Playlists" buttons before playlists: ![Screenshot_20211211-231643_Firefox.png](https://user-images.githubusercontent.com/27908024/145683701-cf53ad4b-f8fc-497a-8abe-0b1f7924c720.png)
> 
> Wonder if that's a better way

I think it is. It's accessible without scrolling, which is good because I think it's more likely that the user wants to see all playlists than that they want to see the last playlist at the bottom of the list.

**Comment by bragefuglseth** [comment]
I think we can close this now, both the current version and planned facelift of the sidebar show playlists directly.

**Comment by xou816** [comment]
Good catch, closing this thanks
