### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by ArberTu474** [xou816/spot#633]
Hello, I am new to Gnome apps and I really like to develop with GTK platform, but to be honest I have not found a good resource to get started. (Maybe because GTK is not used very much)

I know this request is off topic, but if it would be awesome if someone could suggest me a good resource (not including the docs) on how to use Gnome Builder and GTK 4 platform, or tell how you got stared building Gtk apps 

Sorry if I am spamming you, but I would appreciate any reply! (You can close this "issue" any time you want)

**Comment by bragefuglseth** [comment]
That depends on what language you want to work with. Since you’re asking in a Rust/GTK project, I assume that you want to use Rust. You’ll need to learn [gtk-rs](https://gtk-rs.org), preferably through [the book](https://gtk-rs.org/gtk4-rs/stable/latest/book). You can also have a look at [Relm4](https://relm4.org).

The [GNOME Developer Portal](https://developer.gnome.org) may be of interest to you.

There are many other, better places to ask questions as well:
- [The GNOME Newcomers chat room on Matrix](https://matrix.to/#/#newcomers:gnome.org) is good for asking newbie questions. If you want helpful results, be specific in your questions.
- [The GTK chat room on Matrix](https://matrix.to/#/#gtk:gnome.org) may be helpful when you know your way around GTK a little better, and can ask more direct technical questions.
- [GNOME’s discussion forum](https://discourse.gnome.org)
- [r/gtk](https://reddit.com/r/gtk)

Keep in mind that GTK is a big toolkit with a lot to learn, and there isn’t one single guide to just take you from beginner to pro. You’ll find yourself overwhelmed in the beginning, but things will start to make sense if you follow instructions, try to understand more and more of the code and experiment for yourself.

**Comment by bragefuglseth** [comment]
Personally, I got started by learning [Rust](https://rust-lang.org). To use GTK, you should have a pretty thorough understanding of the language you want to use. After that, I went through a large part of the gtk-rs book, revisiting chapters I didn’t understand after some time. I’ve also learned a lot by hanging around in GNOME’s social spaces on Matrix, Reddit and Discourse, so I definitely recommend to join them!

One tip is to make it a habit to use the docs as early as possible. You have the main GTK docs for C, and the docs specific to GTK for your language. If you understand how the main GTK docs for C are connected to your programming language, you’ll be all set once you know where the bits and pieces go.

**Comment by bragefuglseth** [comment]
To try building a project in GNOME Builder, just open Builder, click «Clone Repository», paste this URL: [https://gitlab.gnome.org/World/Solanum.git](https://gitlab.gnome.org/World/Solanum.git), confirm, wait for things to load properly, click the play button and see what happens!

**Comment by ArberTu474** [comment]
Thank you very much. I didn't expect any replies. You gave me some amazing resorses to follow.
I am excited to get started 😊. Thank you again!

**Comment by xou816** [comment]
Thanks a lot @bragefuglseth  :)
