### ISSUE TITLE
Build Fails on Ubuntu 23.04 Lunar on Armhf/Armv7h

### ISSUE THREAD

**Issue by nathan-2006** [xou816/spot#672]
Hello!

Absolutely fantastic project you've got going on here.  I've been trying to build Spot on Ubuntu 23.04 Lunar on Armhf/Armv7h and I've repeatedly been getting stuck at a syntax error right towards the end of the building process; I have all needed build dependencies installed to build Spot.

[26/30] Generating src/blueprints with a custom command
FAILED: src 
/usr/bin/blueprint-compiler batch-compile src/. ../src ../src/app/components/album/album.blp ../src/app/components/artist/artist.blp ../src/app/components/artist_details/artist_details.blp ../src/app/components/details/album_header.blp ../src/app/components/details/details.blp ../src/app/components/details/release_details.blp ../src/app/components/device_selector/device_selector.blp ../src/app/components/headerbar/headerbar.blp ../src/app/components/library/library.blp ../src/app/components/login/login.blp ../src/app/components/now_playing/now_playing.blp ../src/app/components/playback/playback_controls.blp ../src/app/components/playback/playback_info.blp ../src/app/components/playback/playback_widget.blp ../src/app/components/playlist/song.blp ../src/app/components/playlist_details/playlist_details.blp ../src/app/components/playlist_details/playlist_header.blp ../src/app/components/playlist_details/playlist_headerbar.blp ../src/app/components/saved_playlists/saved_playlists.blp ../src/app/components/saved_tracks/saved_tracks.blp ../src/app/components/search/search.blp ../src/app/components/selection/selection_toolbar.blp ../src/app/components/settings/settings.blp ../src/app/components/user_details/user_details.blp ../src/app/components/scrolling_header/scrolling_header.blp ../src/app/components/sidebar/create_playlist.blp ../src/app/components/sidebar/sidebar_row.blp ../src/window.blp

The Meson command I used prior to running `ninja install -C target` was `meson target -Dbuildtype=release -Doffline=false --prefix="$HOME/.local"`

Help would be greatly appreciated and thank you.

**Comment by svenlinker** [comment]
I experience the same issue on Fedora 38 on AMD64. 

 /usr/bin/blueprint-compiler batch-compile src/. ../src ../src/app/components/album/album.blp ../src/app/components/artist/artist.blp ../src/app/components/artist_details/artist_details.blp ../src/app/components/details/album_header.blp ../src/app/components/details/details.blp ../src/app/components/details/release_details.blp ../src/app/components/device_selector/device_selector.blp ../src/app/components/headerbar/headerbar.blp ../src/app/components/library/library.blp ../src/app/components/login/login.blp ../src/app/components/now_playing/now_playing.blp ../src/app/components/playback/playback_controls.blp ../src/app/components/playback/playback_info.blp ../src/app/components/playback/playback_widget.blp ../src/app/components/playlist/song.blp ../src/app/components/playlist_details/playlist_details.blp ../src/app/components/playlist_details/playlist_header.blp ../src/app/components/playlist_details/playlist_headerbar.blp ../src/app/components/saved_playlists/saved_playlists.blp ../src/app/components/saved_tracks/saved_tracks.blp ../src/app/components/search/search.blp ../src/app/components/selection/selection_toolbar.blp ../src/app/components/settings/settings.blp ../src/app/components/user_details/user_details.blp ../src/app/components/scrolling_header/scrolling_header.blp ../src/app/components/sidebar/create_playlist.blp ../src/app/components/sidebar/sidebar_row.blp ../src/window.blp
error: Could not determine what kind of syntax is meant here
at ../src/app/components/album/album.blp line 4 column 10:
   4 |template $AlbumWidget : Adw.Bin {
     |         ^

Could this be due to an old version of blueprint-compiler? (Fedora is still on 0.6.0)

**Comment by svenlinker** [comment]
After updating blueprint-compiler to 0.8.1 manually, I was able to build spot without the error.

**Comment by Diegovsky** [comment]
Hey, thank you for taking interest in the project & submitting an issue! I'm glad you found a fix, so Im closing this :)
