### ISSUE TITLE
Play-button looking wrong with Matcha GTK-Theme

### ISSUE THREAD

**Issue by kleinHeiti** [xou816/spot#69]
I have installed Matcha-sea as my GTK-theme (I use Manjaro Gnome Edition).
With this theme, the play button looks a bit squashed. This is not the case when I use Adwaita as my desktop theme.

![Bildschirmfoto vom 2021-02-18 14-52-27](https://user-images.githubusercontent.com/54942072/108367516-d8060280-71f9-11eb-864b-9f16ca8fa0ac.png)

![Bildschirmfoto vom 2021-02-18 14-53-14](https://user-images.githubusercontent.com/54942072/108367549-de947a00-71f9-11eb-9db9-7f9dd7dd189e.png)

**Comment by xou816** [comment]
Hi! Thanks for the report :) I'm too busy right now to try the app with different themes -- if you or someone else finds a reasonable fix, I'll gladly merge it but I won't investigate this right now, sorry!

**Comment by eladyn** [comment]
Hi!

I did some investigation and I'm pretty sure that this was a bug on the Matcha theme side. They had, some time ago, [this line](https://github.com/vinceliuice/Matcha-gtk-theme/blob/d6aa53fe85f62c34291254275787b7e71218f46d/src/gtk-3.0/gtk-dark-sea.css#L4631) in the theme which caused this strange ellipsis look for circular buttons.

This should, however, have been fixed in version **2021-01-01**, but the flathub version still seems to be on **2019-07** ([see here](https://github.com/flathub/org.gtk.Gtk3theme.Matcha-sea/blob/aa7ba28b29361c4613d4df8c56eda81771b5000a/org.gtk.Gtk3theme.Matcha-sea.json#L23)) :fearful:.

So you probably have those options:
- don't use flatpak for spot
- don't use the flathub but a locally built version of the Matcha-sea theme
- get the flathub version updated (I don't know this publishing process works, so no idea how)

Hope this helps!

**Comment by xou816** [comment]
Oh thank you @eladyn that's quite helpful! Looks like it could be it! If that's the case, it should be as easy as submitted a PR to the repo you linked to update the Matcha theme on flathub

**Comment by eladyn** [comment]
I just created [a PR](https://github.com/flathub/org.gtk.Gtk3theme.Matcha-sea/pull/2) that would update the upstream URL. Hope it gets merged soon :grinning:

**Comment by kleinHeiti** [comment]
Thanks for the help. I have seen that the PR has been accepted.

Since this is obviously a theming problem, the issue can actually be closed here.

What do you think?

**Comment by xou816** [comment]
Sure, let's close this! Thank you both!
